### ISSUE TITLE
[Bug]: Can't get package working with SvelteKit

### ISSUE THREAD

**Issue by davidcallanan** [blocknative/onboard#719]
### Current Behavior

I'm not sure if this is a bug with this library or a bug with [sveltekit](https://kit.svelte.dev/), but I am [having trouble importing this library](https://stackoverflow.com/questions/69302056/sveltekit-cannot-import-onboard-js) in a SvelteKit project.

I have installed `bnc-onboard` and when starting the dev server, I get the following error:

![](https://i.stack.imgur.com/M2B5g.png)

etc etc etc.

### Expected Behavior

Package imports successfully with no error.

### Steps To Reproduce

1. `npm i -g pnpm`
2. `npm init svelte@next my-app`
3. `cd my-app`
4. `pnpm i bnc-onboard`
5. Inside one of the svelte files, e.g. `index.svelte`, add `import Onboard from "bnc-onboard";`
6. Start dev server: `pnpm run dev`

### Onboard Version

latest

### Node Version

v16.6.2

### Relevant log output

```shell
C:\Users\David\Documents\git\xxx>pnpm run dev

> xxx@0.0.1 dev C:\Users\David\Documents\git\xxx
> svelte-kit dev

Pre-bundling dependencies:
  svelte/store
  svelte
  bnc-onboard
  svelte/animate
  svelte/easing
  (...and 3 more)
(this will be run only when your dependencies or config have changed)
 > node_modules/.pnpm/@keystonehq+bc-ur-registry-eth@0.6.11/node_modules/@keystonehq/bc-ur-registry-eth/dist/bc-ur-registry-eth.cjs.development.js:7:27: error: Could not resolve "@keystonehq/bc-ur-registry" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    7 │ var bcUrRegistry = require('@keystonehq/bc-ur-registry');
      ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> Build failed with 1 error:
node_modules/.pnpm/@keystonehq+bc-ur-registry-eth@0.6.11/node_modules/@keystonehq/bc-ur-registry-eth/dist/bc-ur-registry-eth.cjs.development.js:7:27: error: Could not resolve "@keystonehq/bc-ur-registry" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
Error: Build failed with 1 error:
node_modules/.pnpm/@keystonehq+bc-ur-registry-eth@0.6.11/node_modules/@keystonehq/bc-ur-registry-eth/dist/bc-ur-registry-eth.cjs.development.js:7:27: error: Could not resolve "@keystonehq/bc-ur-registry" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    at failureErrorWithLog (C:\Users\David\Documents\git\xxx\node_modules\.pnpm\esbuild@0.13.4\node_modules\esbuild\lib\main.js:1493:15)
    at C:\Users\David\Documents\git\xxx\node_modules\.pnpm\esbuild@0.13.4\node_modules\esbuild\lib\main.js:1151:28
    at runOnEndCallbacks (C:\Users\David\Documents\git\xxx\node_modules\.pnpm\esbuild@0.13.4\node_modules\esbuild\lib\main.js:941:63)
    at buildResponseToResult (C:\Users\David\Documents\git\xxx\node_modules\.pnpm\esbuild@0.13.4\node_modules\esbuild\lib\main.js:1149:7)
    at C:\Users\David\Documents\git\xxx\node_modules\.pnpm\esbuild@0.13.4\node_modules\esbuild\lib\main.js:1258:14
    at C:\Users\David\Documents\git\xxx\node_modules\.pnpm\esbuild@0.13.4\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (C:\Users\David\Documents\git\xxx\node_modules\.pnpm\esbuild@0.13.4\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (C:\Users\David\Documents\git\xxx\node_modules\.pnpm\esbuild@0.13.4\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:475:12)
 ERROR  Command failed with exit code 1.
```

### Anything else?

Operating system: Windows 10

**Comment by taylorjdawson** [comment]
@davidcallanan ping :)

**Comment by davidcallanan** [comment]
@taylorjdawson That particular error seems to be gone, but now there's another error.

![image](https://user-images.githubusercontent.com/40340425/139855856-1a40ae86-15a2-4604-bd5b-13c2e734efbc.png)

Anyway, don't worry about it, I've switched to using Web3Modal for the time being. This is not a high priority for me.

**Comment by theurgi** [comment]
@taylorjdawson @davidcallanan see https://github.com/blocknative/onboard/issues/762#issuecomment-997246672 for a solution if still interested.

**Comment by taylorjdawson** [comment]
@davidcallanan closing in leu of @theurgi's [solution](https://github.com/blocknative/onboard/issues/762#issuecomment-997246672).
